export const products = [
    {
        id: "1",
        name: "Royal Banarasi Silk Saree",
        description: "Handwoven in Varanasi, this deep maroon saree features intricate gold zari work.",
        price: 45000,
        category: "Sarees",
        image: "https://images.unsplash.com/photo-1610189012906-47833cc180bb?q=80&w=2070&auto=format&fit=crop",
        isNew: true,
    },
    {
        id: "2",
        name: "Forest Green Kanjivaram",
        description: "A classic Kanjivaram silk saree in emerald green with a contrasting gold border.",
        price: 38000,
        category: "Sarees",
        image: "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?q=80&w=1974&auto=format&fit=crop",
        isNew: false,
    },
    {
        id: "3",
        name: "Midnight Blue Georgette",
        description: "Lightweight georgette saree with hand-embroidered sequins, perfect for evening wear.",
        price: 22000,
        category: "Sarees",
        image: "https://images.unsplash.com/photo-1583391733956-6c78276477e2?q=80&w=2070&auto=format&fit=crop",
        isNew: true,
    },
    {
        id: "4",
        name: "Golden Tissue Silk",
        description: "Pure tissue silk saree in antique gold, radiating royal elegance.",
        price: 55000,
        category: "Sarees",
        image: "https://images.unsplash.com/photo-1621644783788-b7a42168923a?q=80&w=1979&auto=format&fit=crop",
        isNew: false,
    },
    {
        id: "5",
        name: "Ruby Red Bridal Lehenga",
        description: "Intricately embroidered raw silk lehenga for the modern bride.",
        price: 125000,
        category: "Lehengas",
        image: "https://images.unsplash.com/photo-1595180470200-a5445209351e?q=80&w=2070&auto=format&fit=crop",
        isNew: true,
    },
    {
        id: "6",
        name: "Ivory Chanderi Saree",
        description: "Delicate Chanderi silk cotton saree with small gold motifs.",
        price: 18000,
        category: "Sarees",
        image: "https://images.unsplash.com/photo-1608643640228-56961cf0988e?q=80&w=1974&auto=format&fit=crop",
        isNew: false,
    }
];
